# Generated by Django 2.2.14 on 2020-07-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerInd', '0003_auto_20200729_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorlist',
            options={'managed': False},
        ),
    ]
