# Generated by Django 2.2.14 on 2020-11-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('window_username', models.CharField(db_column='WindowUsername', max_length=255, primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='Active')),
            ],
            options={
                'db_table': 'FleetDataCollectionAdmins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomicilePermissions',
            fields=[
                ('domicile_permission_id', models.AutoField(db_column='FleetDataCollectionDomicilePermissionId', primary_key=True, serialize=False)),
                ('window_username', models.CharField(db_column='WindowUsername', max_length=255)),
                ('domicile', models.CharField(db_column='Domicile', max_length=5)),
            ],
            options={
                'db_table': 'FleetDataCollectionDomicilePermissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M5DriverVehicleDataConfirmations',
            fields=[
                ('unit_number', models.CharField(db_column='UnitNumber', max_length=20, primary_key=True, serialize=False)),
                ('pms', models.CharField(db_column='PMS', max_length=7)),
                ('class2', models.BooleanField(db_column='Class2')),
            ],
            options={
                'db_table': 'FleetDataCollectionM5DriverVehicleDataConfirmations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WUPermissions',
            fields=[
                ('wu_permission_id', models.AutoField(db_column='FleetDataCollectionWUPermissionId', primary_key=True, serialize=False)),
                ('window_username', models.CharField(db_column='WindowUsername', max_length=255)),
                ('wu', models.CharField(db_column='WU', max_length=4)),
            ],
            options={
                'db_table': 'FleetDataCollectionWUPermissions',
                'managed': False,
            },
        ),
    ]
