# Generated by Django 2.2.14 on 2020-11-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleetDataCollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYC_DOTR_UNIT_MAIN',
            fields=[
                ('unit_no', models.CharField(db_column='UNIT_NO', max_length=30, primary_key=True, serialize=False)),
                ('class1', models.CharField(db_column='CLASS1', max_length=4)),
                ('make', models.CharField(db_column='MAKE', max_length=30)),
                ('model', models.CharField(db_column='MODEL', max_length=30)),
                ('domicile', models.CharField(db_column='USING_DEPT_NO', max_length=30)),
                ('parking_loc_name', models.CharField(db_column='PARKING_LOC_NAME', max_length=40)),
            ],
            options={
                'db_table': 'NYC_DOTR_UNIT_MAIN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEmployees',
            fields=[
                ('pms', models.CharField(db_column='PMS#', max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='F-Name', max_length=255)),
                ('last_name', models.CharField(db_column='L-Name', max_length=255)),
                ('lv', models.CharField(db_column='Lv', max_length=255)),
            ],
            options={
                'db_table': 'tblEmployees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWorkUnitDivisionJoeSubs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('wu', models.CharField(db_column='WU', max_length=4, unique=True)),
                ('div', models.CharField(db_column='DIV', max_length=255)),
                ('wu_desc', models.CharField(db_column='Work Unit Description', max_length=255)),
                ('div_group', models.CharField(db_column='Division Group', max_length=255)),
                ('subdiv', models.CharField(db_column='SubDivision', max_length=255)),
            ],
            options={
                'db_table': 'tblWorkUnitDivisionJoeSubs',
                'managed': False,
            },
        ),
    ]
