# Generated by Django 2.2.14 on 2020-11-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleetDataCollection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEmployees',
            fields=[
                ('pms', models.CharField(db_column='PMS#', max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='F-Name', max_length=255)),
                ('last_name', models.CharField(db_column='L-Name', max_length=255)),
                ('wu', models.CharField(db_column='WU', max_length=4)),
            ],
            options={
                'db_table': 'tblEmployees',
                'managed': False,
            },
        ),
    ]
