# Generated by Django 2.2.14 on 2020-11-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleetDataCollection', '0002_tblemployees'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYC_DOTR_UNIT_MAIN',
            fields=[
                ('unit_no', models.CharField(db_column='UNIT_NO', max_length=30, primary_key=True, serialize=False)),
                ('class1', models.CharField(db_column='CLASS1', max_length=4)),
                ('make', models.CharField(db_column='MAKE', max_length=30)),
                ('model', models.CharField(db_column='MODEL', max_length=30)),
                ('domicile', models.CharField(db_column='USING_DEPT_NO', max_length=30)),
            ],
            options={
                'db_table': 'NYC_DOTR_UNIT_MAIN',
                'managed': False,
            },
        ),
    ]
