# Generated by Django 2.2.14 on 2020-07-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerInd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatordata',
            options={'managed': False, 'ordering': ['-record_id']},
        ),
        migrations.AlterModelOptions(
            name='indicatorlist',
            options={'managed': False, 'ordering': ['-indicator_id']},
        ),
    ]
