# Generated by Django 2.2.14 on 2020-07-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerInd', '0002_auto_20200728_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatordata',
            options={'managed': False},
        ),
    ]
