# Generated by Django 2.2.14 on 2020-07-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerInd', '0004_auto_20200730_1615'),
        ('PerInd', '0004_auto_20200730_1608'),
    ]

    operations = [
    ]
