# Generated by Django 2.2.14 on 2021-01-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblChanges',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(db_column='UpdatedOn')),
                ('updated_by_pms', models.CharField(db_column='UpdatedByPMS', max_length=255)),
                ('updated_to_pms', models.CharField(db_column='UpdatedToPMS', max_length=255)),
                ('new_value', models.CharField(db_column='NewValue', max_length=255)),
                ('column_name', models.CharField(db_column='ColumnName', max_length=255)),
            ],
            options={
                'db_table': 'tblChanges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDOTSiteFloors',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('floor_id', models.CharField(db_column='FloorId', max_length=255, unique=True)),
                ('floor', models.CharField(db_column='Floor', max_length=5)),
                ('square_footage', models.BigIntegerField(db_column='SquareFootage')),
            ],
            options={
                'db_table': 'tblDOTSiteFloors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDOTSiteFloorSiteTypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblDOTSiteFloorSiteTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDOTSites',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_column='SiteId', max_length=255, unique=True)),
                ('pms_loc_cd', models.CharField(db_column='PMSLocCd', max_length=255)),
                ('site', models.CharField(db_column='Site', max_length=255)),
                ('address', models.CharField(db_column='Address', max_length=255)),
            ],
            options={
                'db_table': 'tblDOTSites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEmployees',
            fields=[
                ('last_name', models.CharField(db_column='L-Name', max_length=255)),
                ('first_name', models.CharField(db_column='F-Name', max_length=255)),
                ('pms', models.CharField(db_column='PMS#', max_length=7, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('office_title', models.CharField(db_column='OfficeTitle', max_length=255)),
                ('abc_group', models.CharField(db_column='ABCGroup', max_length=1)),
                ('lv', models.CharField(db_column='Lv', max_length=255)),
            ],
            options={
                'db_table': 'tblEmployees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWorkUnitDivisionJoeSubs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('wu', models.CharField(db_column='WU', max_length=4, unique=True)),
                ('div', models.CharField(db_column='DIV', max_length=255)),
                ('wu_desc', models.CharField(db_column='Work Unit Description', max_length=255)),
                ('div_group', models.CharField(db_column='Division Group', max_length=255)),
                ('subdiv', models.CharField(db_column='SubDivision', max_length=255)),
            ],
            options={
                'db_table': 'tblWorkUnitDivisionJoeSubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDOTSiteTypes',
            fields=[
                ('site_type_id', models.AutoField(db_column='SiteTypeId', primary_key=True, serialize=False)),
                ('site_type', models.CharField(db_column='SiteType', max_length=255)),
                ('site_description', models.CharField(db_column='SiteDescription', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TblOfficeTitles',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('office_title', models.CharField(db_column='OfficeTitle', max_length=255)),
                ('active', models.BooleanField(db_column='Active')),
            ],
        ),
        migrations.CreateModel(
            name='TblPermissions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('windows_username', models.CharField(db_column='WindowsUserName', max_length=255)),
                ('pms', models.ForeignKey(db_column='PMS', on_delete=django.db.models.deletion.DO_NOTHING, to='OrgChartPortal.TblEmployees')),
                ('wu', models.ForeignKey(db_column='WU', on_delete=django.db.models.deletion.DO_NOTHING, to='OrgChartPortal.TblWorkUnitDivisionJoeSubs', to_field='wu')),
            ],
        ),
    ]
